# -*- coding: utf-8 -*-
{
    "name": " VENTES: ",
    'summary': """Gestion des ventes de Sheznou""",
    "version": "15.0.1.0.0",
    "author":"Mouhamadou Moustapha DIALLO, Mouhamadou Hafiz KA et Ali Adilani EL FAYAZ ",
    "website" : "",
    "category" : "", 
    "depends" : ['product','mrp','contacts','sale','purchase','repair','project'],
    'description': """ ventes """,
    'data': [    
           'views/produit.xml',
           'views/achat.xml',
           'views/sale.xml',
           'views/icron_achat.xml',
           'views/projet.xml',
        #    'views/production.xml',
          #'views/icron_produit.xml',
          #'views/invoice.xml',
          #'views/sequence_produit.xml',
          # 'views/menu.xml',
          # 'security/ir.model.access.csv',
          #'security/security.xml',
    
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'maintainer' :'Mouhamadou Moustapha DIALLO',
    'support': 'taftaf1949@gmail.com',
}